### ISSUE TITLE
whereNotIn() must be of the type array

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#86]
Hello,

So I was thing to do the following query:

`````
SELECT `orig_id` FROM `RPTC` WHERE `id` NOT IN (SELECT `id` FROM `PCT`)
`````

My code was:
`````
// Sub Query
$query2 = $db->table("PCT")->select("id");

// Main Query
$query = $db->table("RPTC")
			->select("orig_id")
			->whereNotIn("id", $db->subQuery($query2));
`````

However I got this error message:
`````
 Catchable fatal error: Argument 2 passed to Pixie\QueryBuilder\QueryBuilderHandler::whereNotIn() must be of the type array, object given, called
`````

Is there any specific reason why Pixie doesn't allow for a sub-query as the `whereIn` / `whereNotIn` second parameter? How can this be accomplished? Apparently a simple `where()` accepts sub-queries. 

Thank you.

**Comment by TCB13** [comment]
Side Note: I'm aware I could use `LEFT JOIN` in combination with `WHERE PCT.id IS NULL` to accomplish the same result, however the ability to include the sub-queries can become useful in other situations...

**Comment by marc937** [comment]
Use
$query = $db->table("RPTC")
            ->select("orig_id")
            ->where($db->raw('`id` NOT IN (SELECT `id` FROM `PCT`)'));

**Comment by TCB13** [comment]
@marc937 shouldn't `subQuery()` actually work?

**Comment by marc937** [comment]
Yes it should. This issue could be marked as enhancement.

**Comment by usmanhalalit** [comment]
For now please use `Raw`.

**Comment by TCB13** [comment]
@usmanhalalit thanks, that's what I've been doing.

**Comment by neoascetic** [comment]
Have same problem

**Comment by usmanhalalit** [comment]
@TCB13 can you please update and check if the solution works?
I just merged #99

**Comment by TCB13** [comment]
@usmanhalalit the issue seems to be fixed on `whereIn()` however the problem is still present on `whereNotIn()`.
